{% set name = "imaginairy" %}
{% set version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brycedrennan/imaginAIry/archive/{{ version }}.tar.gz
  sha256: 0b60ba590d0360d38b43dbd19e4639f266667cd3341dc5cd9b4398f578624e8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - imagine = imaginairy.cmds:imagine_cmd
    - aimg = imaginairy.cmds:aimg

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click <8
    - click-shell
    - click-help-colors
    - protobuf !=3.20.2, !=3.19.5
    - facexlib
    - fairscale >=0.4.4  # for vendored blip
    - ftfy  # for vendored clip
    - pytorch >=1.2.0
    - numpy
    - tqdm
    - diffusers
    - imageio >=2.9.0
    - pillow >=8.0.0
    - psutil
    - pytorch-lightning >=1.4.2
    - omegaconf >=2.1.1
    - open-clip-torch
    - py-opencv
    - requests
    - einops >=0.3.0
    - safetensors
    - timm >=0.4.12  # for vendored blip
    - torchdiffeq
    - transformers >=4.19.2
    - torchmetrics >=0.6.0
    - torchvision >=0.13.1
    - kornia >=0.6
    - xformers

test:
  imports:
    - imaginairy
  requires:
    - pip
  commands:
    - pip check
    - imagine --help
    - aimg --help

about:
  home: https://github.com/brycedrennan/imaginAIry
  summary: AI imagined images. Pythonic generation of stable diffusion images.
  description: |
    AI imagined images. Pythonic generation of stable diffusion images.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/brycedrennan/imaginAIry
  dev_url: https://github.com/brycedrennan/imaginAIry

extra:
  recipe-maintainers:
    - brycedrennan
    - jan-janssen
